/* eslint-disable react-refresh/only-export-components */
import React, { createContext, useContext, useState } from 'react';

export type Language = 'hu' | 'en' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  hu: {
    // Sidebar & Navigation
    appName: 'SmartFarm Raktár',
    version: 'Verzió 1.2.0',
    navDashboard: 'Dashboard',
    navMaterials: 'Anyagok',
    navNewMaterial: 'Új anyag',
    navMovements: 'Készletmozgások',
    navQrCodes: 'QR-kódok',
    navUsers: 'Felhasználók',
    navAllowedEmails: 'Engedélyezett e-mailek',
    navSettings: 'Beállítások',
    navLogout: 'Kijelentkezés',

    // Header & General UI
    roleAdmin: 'Raktárvezető',
    roleOperator: 'Raktári dolgozó',
    roleKezelo: 'Kezelő',
    notifTitle: 'Legutóbbi készletmozgások',
    notifEmpty: 'Még nem történt készletmozgás.',
    notifAll: 'Összes mozgás megtekintése',
    notifAriaLabel: 'Értesítések',
    toastTitle: 'Készletmozgás történt!',
    searchPlaceholder: 'Keresés anyag, azonosító vagy hely szerint...',
    searchResultsTitle: 'Keresési találatok',
    noSearchResults: 'Nincs a keresési feltételnek megfelelő anyag.',
    pressEnterToView: 'Nyomj ENTER-t a megtekintéshez',
    qrScanBtn: 'QR Beolvasás',
    demoNotice: 'Jelenleg offline Demó / LocalStorage üzemmódban fut a rendszer.',
    demoLink: 'Supabase csatlakozási adatok megadása',
    loading: 'Töltés...',
    save: 'Mentés',
    saveData: 'Adatok mentése',
    saving: 'Mentés...',
    savingData: 'Adatok mentése...',
    cancel: 'Mégse',
    btnExportCSV: 'Exportálás CSV-be',

    // Dashboard Overview
    dbTitle: 'Főáttekintő dashboard',
    dbSubtitle: 'Áttekintés a raktár készletéről és a legfontosabb mutatókról.',
    cardTotalMaterials: 'Összes anyag',
    cardLowStock: 'Alacsony készlet',
    cardTodayMovements: 'Mai mozgások',
    levelGreen: 'Zöld szint (>70%)',
    levelYellow: 'Sárga szint (40-70%)',
    levelRed: 'Piros szint (<40%)',
    criticalStockTitle: 'Kritikus készletű anyagok',
    viewAllCritical: 'Összes kritikus anyag megtekintése',
    categoryDistribution: 'Kategória szerinti megoszlás',
    totalText: 'ÖSSZESEN',
    statStatus: 'STÁTUSZ',
    statId: 'AZONOSÍTÓ',
    statName: 'NÉV',
    statStock: 'KÉSZLET',
    statMax: 'MAX',
    statLevel: 'SZINT',
    statLocation: 'HELY',
    comparedToLastWeek: 'az előző héthez képest',
    comparedToYesterday: 'az előző naphoz képest',
    dbConsumptionTitle: 'Havi fogyasztási trend',
    dbForecastTitle: 'Készlet-előrejelzés',
    dbForecastStable: 'Minden készletszint stabil a jelenlegi fogyasztás alapján.',
    dbForecastRisk: 'Kifogyási kockázat',
    dbForecastDaysLeft: 'napra elegendő készlet',
    dbForecastReorder: 'Javasolt utánrendelés',
    dbDemoDataNotice: 'Demó adatokat lát (valós készletmozgások hiányában)',

    // Materials View
    matTitle: 'Raktárkészlet',
    matSubtitle: 'Az összes regisztrált anyag listája és aktuális készletszintje.',
    matCategories: 'Kategóriák:',
    matAll: 'Mind',
    matSearch: 'Keresés...',
    matNoResults: 'Nincs találat a keresési feltételeknek megfelelően.',
    matCardView: 'Kártya nézet',
    matTableView: 'Táblázat nézet',
    matActions: 'Műveletek',
    matEdit: 'Módosítás',
    matDelete: 'Törlés',
    matIntake: 'Bevételezés',
    matCheckout: 'Kiadás',
    matPrint: 'Nyomtatás',
    matDeactivate: 'Inaktiválás',
    matRestore: 'Visszaállítás',
    matActiveTab: 'Aktív készlet',
    matInactiveTab: 'Inaktív archívum',
    matDeactivateConfirm: 'Biztosan inaktívvá szeretnéd tenni a(z) {name} anyagot? Nem lehet majd bevételezni vagy kivenni.',
    matDeactivateTitle: 'Anyag inaktiválása',
    matDeactivateWarning: 'Inaktív állapotban az anyag nem bevételezhető és nem adható ki, és a QR-kódjának beolvasása is blokkolva lesz.',
    matDeactivateBtn: 'Inaktiválás megerősítése',
    matRestoreConfirm: 'Biztosan vissza szeretnéd állítani a(z) {name} anyagot az aktívak közé?',
    matRestoreTitle: 'Anyag visszaállítása',
    matRestoreWarning: 'A visszaállítás után az anyag újra bevételezhető és kiadható lesz, valamint a QR-kód beolvasása is működni fog.',
    matRestoreBtn: 'Visszaállítás megerősítése',
    matErrorInactiveScan: 'Figyelem! A(z) "{name}" ({id}) anyag jelenleg inaktív. Tranzakció nem végezhető vele!',
    matErrorGepScan: 'Ez a termék GEP-es és nincs joga hozzá!',
    matGepNoPermissionTitle: 'Nincs jogosultság',
    matGepNoPermissionBody: 'A(z) "{name}" ({id}) termék GEP-es és nincs jogosultságod hozzá!',
    ok: 'Rendben',

    // Movements View
    movTitle: 'Készletmozgások naplója',
    movSubtitle: 'A raktárban történt bevételezések és kiadások időrendi listája.',
    movNoResults: 'Nincs még rögzített készletmozgás.',
    movColType: 'TÍPUS',
    movColMaterial: 'ANYAG',
    movColQty: 'MENNYISÉG',
    movColDate: 'DÁTUM',
    movColUser: 'FELHASZNÁLÓ',
    movColNotes: 'MEGJEGYZÉS',
    movTypeIntake: 'Bevétel',
    movTypeCheckout: 'Kivétel',

    // QR Codes View
    qrTitle: 'QR-kód Generátor',
    qrSubtitle: 'Itt nyomtathatsz QR-kódot a raktári anyagokhoz a könnyebb beazonosítás és beolvasás érdekében.',
    qrColAction: 'Nyomtatás',
    qrDeselectAll: 'Kijelölés törlése',
    qrSelectAll: 'Összes kijelölése',
    qrPrintSelected: 'Kijelöltek nyomtatása ({count} db)',
    qrSearchPlaceholder: 'Keresés név, ID vagy helyszín alapján...',
    qrSelectedCounter: 'Kijelölve: {selected} / {total} anyag',
    qrNoMatchingMaterials: 'Nincs a keresési feltételnek megfelelő anyag.',
    qrSinglePrintTitle: 'Egyedi nyomtatás',
    qrNoLocation: 'Nincs megadva',
    qrPrintDocumentTitle: 'SmartFarm - QR Kódok A4 Nyomtatása ({count} db)',
    qrScanTitle: 'QR-Kód beolvasása',
    qrClose: 'Bezárás',
    qrCameraLabel: 'Kamera:',
    qrCameraFallback: 'Kamera',
    qrManualLabel: 'Anyag Azonosító (pl. PRM-001)',
    qrManualBtn: 'Azonosító Lekérése',
    qrBackToCamera: 'Vissza a kamerához',
    qrTypeManual: 'Kód megadása gépeléssel',
    qrErrorNoCamera: 'Nem található kamera. Kérjük, használd a manuális kódbevitelt.',
    qrErrorSecureContext: 'Kamera hozzáférés hiba: A böngészők biztonsági okokból csak biztonságos (HTTPS vagy localhost) kapcsolaton engedélyezik a kamerát. Használj HTTPS-t (pl. localtunnel/ngrok) vagy a manuális bevitelt!',
    qrErrorScanFailed: 'Hiba a kamerák keresése közben. Használhatod a manuális bevitelt.',
    qrErrorCameraStart: 'Nem sikerült elindítani a kamerát. Kérjük, engedélyezd a hozzáférést a böngésződben.',
    colCategory: 'Kategória',
    colUnit: 'Mértékegység',
    unitDb: 'db',
    cat_Herbicit: 'Herbicit (Gyomirtó)',
    cat_Insecticit: 'Insecticit (Rovarirtó)',
    cat_Fungicit: 'Fungicit (Gombaölő)',
    cat_Biostimulátor: 'Biostimulátor',
    cat_Permetszerek: 'Permetszerek',
    cat_Műtrágyák: 'Műtrágyák',
    'cat_Szilárd műtrágya': 'Szilárd műtrágya',
    'cat_Folyékony műtrágya': 'Folyékony műtrágya',
    cat_MűtrágyaMind: 'Mindegyik műtrágya',
    cat_MutragyaTipus: 'Műtrágya halmazállapota (típusa):',
    cat_MutragyaSzilard: 'Szilárd (kg / t)',
    cat_MutragyaFolyekony: 'Folyékony (l)',
    cat_Vetőmagok: 'Vetőmagok',
    cat_Tápok: 'Tápok',
    cat_Adalékanyagok: 'Adalékanyagok',
    cat_Egyéb: 'Egyéb',
    txLocationLabel: 'Hely',
    txCurrentStock: 'Jelenlegi készlet',
    txTitleAdjustment: 'Készletmódosítás',
    txErrorFailed: 'Tranzakció rögzítése sikertelen.',
    txErrorMaxCapacity: 'A felvenni kívánt mennyiséggel ({total} {unit}) a készlet meghaladná a maximális kapacitást ({max} {unit})! Növeld a maximum kapacitást az anyag szerkesztésénél.',
    txErrorNotEnoughStock: 'Nincs elég készlet! Jelenleg elérhető: {current} {unit}',
    txTypeLabel: 'Művelet Típusa',
    txOptCheckout: 'Kivétel (Kiadás)',
    txOptIntake: 'Bevétel (Töltés)',
    txQtyLabel: 'Mennyiség',
    txNotesLabel: 'Megjegyzés (opcionális)',
    txNotesPlaceholder: 'pl. Napi permetezéshez, megrendelés érkezett...',
    txBtnSubmit: 'Rögzítés',
    mfLabelExpiration: 'Lejárati idő (opcionális)',
    matExpiration: 'Lejárati idő',
    matExpired: 'LEJÁRT!',
    matExpiringSoon: 'Hamarosan lejár',
    matNoExpiration: 'Nincs megadva',
    dbExpiringAlert: 'Lejárati figyelmeztetések',
    mfEditTitle: 'Anyag szerkesztése',
    mfNewTitle: 'Új anyag felvétele',
    mfErrorCamera: 'Nem sikerült hozzáférni a kamerához. Ellenőrizd a böngésző engedélyeket.',
    mfErrorFormat: 'Az azonosítónak HHH-SZSZSZ formátumúnak kell lennie (pl. PRM-001)!',
    mfErrorExists: 'Már létezik anyag ezzel az azonosítóval: ',
    mfErrorQtyPositive: 'A mennyiségeknek nagyobbnak kell lenniük 0-nál.',
    mfErrorQtyMax: 'Az aktuális mennyiség nem lehet nagyobb, mint a maximális készlet.',
    mfErrorSave: 'Hiba történt az anyag mentése során.',
    mfErrorGepRequired: 'Kérjük, válaszd ki a GEP mező értékét!',
    mfLabelId: 'Azonosító',
    mfPlaceholderId: 'pl. PRM-001',
    mfLabelName: 'Anyag Megnevezése',
    mfPlaceholderName: 'pl. Permetszer A',
    mfLabelStartQty: 'Kezdő Mennyiség',
    mfLabelMaxCap: 'Maximális Kapacitás',
    mfUnitPcs: 'Darab (db)',
    mfUnitKg: 'Kilogramm (kg)',
    mfUnitL: 'Liter (l)',
    mfLabelLoc: 'Raktárhely (Szekció-Részleg-Polc)',
    mfPlaceholderLoc: 'pl. A1-01-03',
    mfLabelImage: 'Termékkép készítése vagy feltöltése',
    mfBtnCapture: 'Fénykép készítése',
    mfBtnCancelCapture: 'Mégsem készít képet',
    mfAltPreview: 'Termék előnézet',
    mfBtnChangeImage: 'Kép cseréje',
    mfBtnDeleteImage: 'Kép törlése',
    mfBtnTakePhoto: 'Fotózás kamerával',
    mfBtnUploadPhoto: 'Kép feltöltése',
    mfBtnSaveNew: 'Termék mentése',
    mfBtnSaveEdit: 'Módosítások mentése',

    // Users View
    usrTitle: 'Felhasználók kezelése',
    usrSubtitle: 'A rendszerhez hozzáférő raktári dolgozók és jogosultságok.',
    usrColName: 'NÉV',
    usrColEmail: 'EMAIL',
    usrColRole: 'SZEREPKÖR',
    usrRoleAdmin: 'Raktárvezető (Admin)',
    usrRoleOperator: 'Kezelő (Munkatárs)',
    usrStatusActive: 'Aktív',
    usrNoUsers: 'Nem található felhasználó.',

    // Settings View
    setProfileTitle: 'Profil beállítások',
    setLabelName: 'Név',
    setPlaceholderName: 'Teljes név',
    setLabelEmail: 'Email cím (nem módosítható)',
    setLabelRole: 'Szerepkör (adminisztrációs)',
    setLabelOldPwd: 'Régi jelszó (opcionális)',
    setPlaceholderOldPwd: 'Adja meg a jelenlegi jelszavát',
    setLabelNewPwd: 'Új jelszó (opcionális)',
    setPlaceholderNewPwd: 'Adja meg az új jelszót',
    setForgotPwd: 'Elfelejtetted a régi jelszavad? (Emlékeztető küldése)',
    setLanguageTitle: 'Nyelvválasztás / Language / Sprache',
    setLanguageDesc: 'Válaszd ki a rendszer nyelvét (Select language / Sprache wählen):',
    setAvatarDesc: 'Módosítsd a profilképet a bal alsó gombbal, vagy töröld a jobb alsó gombbal.',
    setSuccessAll: 'A profil adatok és a jelszó is sikeresen frissült!',
    setSuccessPwd: 'Jelszó sikeresen megváltoztatva!',
    setSuccessProfile: 'Profil adatok sikeresen elmentve!',
    setSuccessGeneral: 'Változtatások sikeresen elmentve!',
    setErrorName: 'A név megadása kötelező!',
    setErrorPwdMatch: 'A jelszó módosításához a régi és az új jelszó megadása is kötelező!',
    setErrorPwdLength: 'Az új jelszónak legalább 6 karakterből kell állnia!',
    setDbAdminInfo: 'Adatbázis Rendszergazda Info',
    setDbRefresh: 'Frissítés',
    setDbStorageUsed: 'Összes felhasznált tárhely:',
    setDbMovements: 'Készletmozgások',
    setDbMovementsUnit: 'tranzakció',
    setDbMaterials: 'Anyagok',
    setDbMaterialsUnit: 'tétel',
    setDbAccounts: 'Fiókok',
    setDbAccountsUnit: 'felhasználó',
    setDbFetching: 'Méretek lekérése...',

    statAddedPast7Days: 'az elmúlt 7 napban',
    statNoAddedPast7Days: 'Nincs új tétel az elmúlt 7 napban',
    statCriticalRed: 'kritikus szintre csökkent (<40%)',
    statStockOptimal: 'Minden készletszint optimális',
    statComparedToYesterday: 'a tegnapi naphoz képest',
    statUnchangedYesterday: 'Változatlan a tegnapi naphoz képest',

    // Allowed Emails View
    allowedTitle: 'Engedélyezett e-mailek',
    allowedSubtitle: 'A raktári alkalmazásba regisztrálásra és belépésre jogosult e-mail címek (Raktárvezetői felület).',
    allowedCsvExport: 'CSV Export',
    allowedBtnAdd: 'Új e-mail engedélyezése',
    allowedTotalCount: 'Összesen {count} engedélyezett e-mail cím.',
    allowedSearchPlaceholder: 'Keresés név vagy e-mail...',
    allowedLoading: 'Töltés...',
    allowedColName: 'NÉV / MEGJEGYZÉS',
    allowedColEmail: 'ENGEDÉLYEZETT EMAIL CÍM',
    allowedColDate: 'ENGEDÉLYEZVE DÁTUM',
    allowedColStatus: 'STÁTUSZ',
    allowedColActions: 'MŰVELETEK',
    allowedSelfBadge: '(Saját fiók)',
    allowedDefaultUser: 'Engedélyezett Felhasználó',
    allowedStatusActive: 'Engedélyezve',
    allowedBtnRevoke: 'Visszavonás',
    allowedRevokeTitle: 'Engedély visszavonása',
    allowedRevokeSelfError: 'Saját fiókod regisztrációs engedélyét biztonsági okokból nem vonhatod vissza!',
    allowedRevokeConfirm: 'Biztosan vissza szeretnéd vonni a(z) {email} regisztrációs engedélyét?',
    allowedNoResults: 'Nincs megjeleníthető engedélyezett e-mail cím a megadott keresési feltételek alapján.',
    allowedModalTitle: 'Új e-mail engedélyezése',
    allowedModalDesc: 'Add meg a felvenni kívánt e-mail címet! A felhasználó ezzel az e-mail címmel tud majd regisztrálni és belépni a SmartFarm alkalmazásba.',
    allowedModalLabelEmail: 'E-mail cím *',
    allowedModalLabelName: 'Név / Megjegyzés (Opcionális)',
    allowedModalPlaceholderEmail: 'dolgozo@ceg.hu',
    allowedModalPlaceholderName: 'pl. Nagy Péter (Gépkezelő)',
    allowedModalBtnCancel: 'Mégse',
    allowedModalBtnSubmit: 'Engedélyezés',
    allowedModalBtnLoading: 'Hozzáadás...',
    allowedModalErrorEmailRequired: 'Kérjük, add meg az e-mail címet!',

    // Login View
    loginTitle: 'Bejelentkezés a rendszerbe',
    loginCardTitle: 'Bejelentkezés',
    loginCardSubtitle: 'Lépj be a SmartFarm raktárkezelő rendszerébe',
    loginLabelEmail: 'Email cím',
    loginPlaceholderEmail: 'példa@ceg.hu',
    loginLabelPwd: 'Jelszó',
    loginPlaceholderPwd: '••••••••••••',
    loginBtnSubmit: 'Belépés',
    loginBtnSubmitLoading: 'Belépés...',
    loginRemember: 'Emlékezz rám',
    loginForgotPwdLink: 'Elfelejtett jelszó?',
    loginOrDivider: 'vagy',
    loginNoAccount: 'Nincs fiókod? Regisztráció',
    loginHaveAccount: 'Van már fiókod? Bejelentkezés',

    loginRegisterTitle: 'Regisztráció',
    loginRegisterCardTitle: 'Regisztráció',
    loginRegisterCardSubtitle: 'Hozz létre egy új SmartFarm fiókot',
    loginBtnRegister: 'Regisztráció',
    loginRegisterBtnSubmit: 'Regisztráció',
    loginRegisterBtnSubmitLoading: 'Regisztráció...',
    loginRoleAdmin: 'Raktárvezető (Admin)',
    loginRoleOperator: 'Raktári dolgozó (Kezelő)',
    loginLabelFullName: 'Teljes név',
    loginRegisterPlaceholderName: 'Kovács Gábor',
    loginLabelRole: 'Szerepkör',

    loginForgotCardTitle: 'Elfelejtett jelszó',
    loginForgotCardSubtitle: 'Add meg az e-mail címedet a jelszó-visszaállítási link elküldéséhez',
    loginForgotBtnSubmit: 'Visszaállítási link küldése',
    loginForgotBtnSubmitLoading: 'Küldés...',
    loginForgotBackToLogin: 'Vissza a bejelentkezéshez',

    loginResetCardTitle: 'Új jelszó megadása',
    loginResetCardSubtitle: 'Add meg az új jelszavadat a fiókodhoz',
    loginResetLabelNewPwd: 'Új jelszó',
    loginResetLabelConfirmPwd: 'Új jelszó megerősítése',
    loginResetBtnSubmit: 'Jelszó frissítése',
    loginResetBtnSubmitLoading: 'Módosítás...',

    authErrorEmailRequired: 'Kérjük, add meg az e-mail címedet!',
    authErrorPwdRequired: 'Kérjük, add meg a jelszavadat!',
    authErrorNameRequired: 'Kérjük, add meg a teljes nevedet!',
    authErrorNewPwdRequired: 'Kérjük, add meg az új jelszót!',
    authErrorPwdMismatch: 'A két jelszó nem egyezik meg!',
    authErrorNotAllowed: 'Ez az e-mail cím nincs engedélyezve a SmartFarm rendszerben! Kérjük, vedd fel a kapcsolatot a raktárvezetővel az engedélyezésért.',
    authErrorInvalidCredentials: 'Hibás e-mail cím vagy jelszó. Ellenőrizd a megadott adatokat!',
    authErrorEmailNotConfirmed: 'Az e-mail cím még nincs megerősítve! Kérjük, ellenőrizd a bejövő leveleidet.',
    authErrorUserExists: 'Ezzel az e-mail címmel már regisztráltak a rendszerbe!',
    authErrorPwdWeak: 'Az új jelszónak legalább 6 karakterből kell állnia!',
    authErrorRateLimit: 'Túl sok próbálkozás rövid időn belül! Kérjük, várj egy keveset, majd próbáld újra.',
    authErrorInvalidToken: 'A jelszó-visszaállító link érvénytelen vagy lejárt.',
    authErrorGeneral: 'Hiba történt a művelet során. Kérjük, próbáld újra!',
    authErrorNotRegistered: 'Ez az e-mail cím nincs regisztrálva a rendszerben!',

    authSuccessRegister: 'Sikeres regisztráció! Kérjük, ellenőrizd az e-mail fiókodat a megerősítő linkért.',
    authSuccessRegisterDemo: 'Sikeres regisztráció offline módban! Most már bejelentkezhetsz.',
    authSuccessForgotSent: 'A jelszó-visszaállítási linket elküldtük az e-mail címedre! Kérjük, ellenőrizd a bejövő leveleidet.',
    authSuccessForgotDemo: 'Offline mód: Az e-mail küldést szimuláltuk. Azonosítás sikeres! Most megadhatod az új jelszót.',
    authSuccessResetDone: 'A jelszavad sikeresen megváltozott! Jelentkezz be újra az új jelszóval.',
    authSuccessResetDemo: 'Offline mód: A jelszó sikeresen megváltozott! Most már bejelentkezhetsz az új jelszóval.',
  },
  en: {
    // Sidebar & Navigation
    appName: 'SmartFarm Inventory',
    version: 'Version 1.2.0',
    navDashboard: 'Dashboard',
    navMaterials: 'Materials',
    navNewMaterial: 'New Material',
    navMovements: 'Movements',
    navQrCodes: 'QR Codes',
    navUsers: 'Users',
    navAllowedEmails: 'Allowed Emails',
    navSettings: 'Settings',
    navLogout: 'Logout',

    // Header & General UI
    roleAdmin: 'Warehouse Manager',
    roleOperator: 'Warehouse Worker',
    roleKezelo: 'Operator',
    notifTitle: 'Recent Movements',
    notifEmpty: 'No movements yet.',
    notifAll: 'View all movements',
    notifAriaLabel: 'Notifications',
    toastTitle: 'Stock movement occurred!',
    searchPlaceholder: 'Search by material, code or location...',
    searchResultsTitle: 'Search Results',
    noSearchResults: 'No matching materials found.',
    pressEnterToView: 'Press ENTER to view',
    qrScanBtn: 'Scan QR',
    demoNotice: 'The system is currently running in offline Demo / LocalStorage mode.',
    demoLink: 'Configure Supabase connection settings',
    loading: 'Loading...',
    save: 'Save',
    saveData: 'Save Data',
    saving: 'Saving...',
    savingData: 'Saving Data...',
    cancel: 'Cancel',
    btnExportCSV: 'Export to CSV',

    // Dashboard Overview
    dbTitle: 'Dashboard Overview',
    dbSubtitle: 'Overview of warehouse stock and key performance metrics.',
    cardTotalMaterials: 'Total Materials',
    cardLowStock: 'Low Stock',
    cardTodayMovements: "Today's Movements",
    levelGreen: 'Green level (>70%)',
    levelYellow: 'Yellow level (40-70%)',
    levelRed: 'Red level (<40%)',
    criticalStockTitle: 'Critical Stock Materials',
    viewAllCritical: 'View All Critical Materials',
    categoryDistribution: 'Category Distribution',
    totalText: 'TOTAL',
    statStatus: 'STATUS',
    statId: 'ID',
    statName: 'NAME',
    statStock: 'STOCK',
    statMax: 'MAX',
    statLevel: 'LEVEL',
    statLocation: 'LOCATION',
    comparedToLastWeek: 'compared to last week',
    comparedToYesterday: 'compared to yesterday',
    dbConsumptionTitle: 'Monthly Consumption Trend',
    dbForecastTitle: 'Smart Stock Forecast',
    dbForecastStable: 'All stock levels stable based on current usage.',
    dbForecastRisk: 'Risk of running out',
    dbForecastDaysLeft: 'days of supply left',
    dbForecastReorder: 'Recommended reorder',
    dbDemoDataNotice: 'Showing demo data (no transactions logged yet)',

    // Materials View
    matTitle: 'Warehouse Stock',
    matSubtitle: 'List of all registered materials and their current stock levels.',
    matCategories: 'Categories:',
    matAll: 'All',
    matSearch: 'Search...',
    matNoResults: 'No materials found matching search criteria.',
    matCardView: 'Card View',
    matTableView: 'Table View',
    matActions: 'Actions',
    matEdit: 'Edit',
    matDelete: 'Delete',
    matIntake: 'Intake',
    matCheckout: 'Checkout',
    matPrint: 'Print',
    matDeactivate: 'Deactivate',
    matRestore: 'Restore',
    matActiveTab: 'Active Materials',
    matInactiveTab: 'Inactive Materials / Archive',
    matDeactivateConfirm: 'Are you sure you want to deactivate {name}? Intake and checkout operations will be disabled.',
    matDeactivateTitle: 'Deactivate Material',
    matDeactivateWarning: 'While inactive, the material cannot be checked in or out, and scanning its QR code will be blocked.',
    matDeactivateBtn: 'Confirm Deactivation',
    matRestoreConfirm: 'Are you sure you want to restore {name} to the active stock?',
    matRestoreTitle: 'Restore Material',
    matRestoreWarning: 'After restoration, the material can be checked in and out again, and QR code scanning will function normally.',
    matRestoreBtn: 'Confirm Restoration',
    matErrorInactiveScan: 'Warning! The material "{name}" ({id}) is currently inactive. Transactions are disabled!',
    matErrorGepScan: 'This product is GEP and you do not have permission for it!',
    matGepNoPermissionTitle: 'Access Denied',
    matGepNoPermissionBody: 'The product "{name}" ({id}) is GEP and you do not have permission for it!',
    ok: 'OK',

    // Movements View
    movTitle: 'Inventory Movements Log',
    movSubtitle: 'Chronological list of warehouse intakes and checkouts.',
    movNoResults: 'No inventory movements recorded yet.',
    movColType: 'TYPE',
    movColMaterial: 'MATERIAL',
    movColQty: 'QUANTITY',
    movColDate: 'DATE',
    movColUser: 'USER',
    movColNotes: 'NOTES',
    movTypeIntake: 'Intake',
    movTypeCheckout: 'Checkout',

    // QR Codes View
    qrTitle: 'QR Code Generator',
    qrSubtitle: 'Generate and print QR codes for materials to scan and identify them easily.',
    qrColAction: 'Print',
    qrDeselectAll: 'Clear selection',
    qrSelectAll: 'Select all',
    qrPrintSelected: 'Print selected ({count} pcs)',
    qrSearchPlaceholder: 'Search by name, ID or location...',
    qrSelectedCounter: 'Selected: {selected} / {total} materials',
    qrNoMatchingMaterials: 'No materials match the search criteria.',
    qrSinglePrintTitle: 'Print single QR code',
    qrNoLocation: 'Not specified',
    qrPrintDocumentTitle: 'SmartFarm - A4 QR Code Printing ({count} pcs)',
    qrScanTitle: 'Scan QR Code',
    qrClose: 'Close',
    qrCameraLabel: 'Camera:',
    qrCameraFallback: 'Camera',
    qrManualLabel: 'Material ID (e.g. PRM-001)',
    qrManualBtn: 'Retrieve Material',
    qrBackToCamera: 'Back to Camera',
    qrTypeManual: 'Enter code manually',
    qrErrorNoCamera: 'No camera found. Please use manual code entry.',
    qrErrorSecureContext: 'Camera access error: Browsers only permit camera access over secure connections (HTTPS or localhost) for security reasons. Use HTTPS (e.g. localtunnel/ngrok) or manual entry!',
    qrErrorScanFailed: 'Error searching for cameras. You can use manual entry.',
    qrErrorCameraStart: 'Failed to start camera. Please grant access permission in your browser.',
    colCategory: 'Category',
    colUnit: 'Unit',
    unitDb: 'pcs',
    cat_Herbicit: 'Herbicide',
    cat_Insecticit: 'Insecticide',
    cat_Fungicit: 'Fungicide',
    cat_Biostimulátor: 'Biostimulant',
    cat_Permetszerek: 'Pesticides',
    cat_Műtrágyák: 'Fertilizers',
    'cat_Szilárd műtrágya': 'Solid Fertilizer',
    'cat_Folyékony műtrágya': 'Liquid Fertilizer',
    cat_MűtrágyaMind: 'All Fertilizers',
    cat_MutragyaTipus: 'Fertilizer Type:',
    cat_MutragyaSzilard: 'Solid (kg / t)',
    cat_MutragyaFolyekony: 'Liquid (l)',
    cat_Vetőmagok: 'Seeds',
    cat_Tápok: 'Feeds',
    cat_Adalékanyagok: 'Additives',
    cat_Egyéb: 'Other',
    txLocationLabel: 'Location',
    txCurrentStock: 'Current stock',
    txTitleAdjustment: 'Stock adjustment',
    txErrorFailed: 'Failed to record transaction.',
    txErrorMaxCapacity: 'With the added quantity ({total} {unit}), stock would exceed the maximum capacity ({max} {unit})! Please increase maximum capacity in material settings.',
    txErrorNotEnoughStock: 'Not enough stock! Currently available: {current} {unit}',
    txTypeLabel: 'Transaction Type',
    txOptCheckout: 'Checkout (Withdrawal)',
    txOptIntake: 'Intake (Restock)',
    txQtyLabel: 'Quantity',
    txNotesLabel: 'Notes (optional)',
    txNotesPlaceholder: 'e.g. Daily spraying, order arrived...',
    txBtnSubmit: 'Record',
    mfLabelExpiration: 'Expiration Date (optional)',
    matExpiration: 'Expiration Date',
    matExpired: 'EXPIRED!',
    matExpiringSoon: 'Expiring soon',
    matNoExpiration: 'Not specified',
    dbExpiringAlert: 'Expiration Warnings',
    mfEditTitle: 'Edit Material',
    mfNewTitle: 'Add New Material',
    mfErrorCamera: 'Could not access the camera. Check browser permissions.',
    mfErrorFormat: 'The ID must be in AAA-111 format (e.g. PRM-001)!',
    mfErrorExists: 'Material with this ID already exists: ',
    mfErrorQtyPositive: 'Quantities must be greater than 0.',
    mfErrorQtyMax: 'Current quantity cannot be greater than maximum stock capacity.',
    mfErrorSave: 'An error occurred while saving the material.',
    mfErrorGepRequired: 'Please select the GEP field value!',
    mfLabelId: 'Identifier (ID)',
    mfPlaceholderId: 'e.g. PRM-001',
    mfLabelName: 'Material Name',
    mfPlaceholderName: 'e.g. Pesticide A',
    mfLabelStartQty: 'Initial Quantity',
    mfLabelMaxCap: 'Maximum Capacity',
    mfUnitPcs: 'Pieces (pcs)',
    mfUnitKg: 'Kilograms (kg)',
    mfUnitL: 'Liters (l)',
    mfLabelLoc: 'Storage Location (Section-Aisle-Shelf)',
    mfPlaceholderLoc: 'e.g. A1-01-03',
    mfLabelImage: 'Take or upload product image',
    mfBtnCapture: 'Capture photo',
    mfBtnCancelCapture: 'Cancel photo capture',
    mfAltPreview: 'Product preview',
    mfBtnChangeImage: 'Change image',
    mfBtnDeleteImage: 'Delete image',
    mfBtnTakePhoto: 'Take photo',
    mfBtnUploadPhoto: 'Upload image',
    mfBtnSaveNew: 'Save Product',
    mfBtnSaveEdit: 'Save Changes',

    // Users View
    usrTitle: 'User Management',
    usrSubtitle: 'Warehouse workers and permissions accessing the system.',
    usrColName: 'NAME',
    usrColEmail: 'EMAIL',
    usrColRole: 'ROLE',
    usrRoleAdmin: 'Warehouse Manager (Admin)',
    usrRoleOperator: 'Operator (Worker)',
    usrStatusActive: 'Active',
    usrNoUsers: 'No users found.',

    // Settings View
    setProfileTitle: 'Profile Settings',
    setLabelName: 'Name',
    setPlaceholderName: 'Full name',
    setLabelEmail: 'Email Address (read-only)',
    setLabelRole: 'Role (administrative)',
    setLabelOldPwd: 'Old Password (optional)',
    setPlaceholderOldPwd: 'Enter your current password',
    setLabelNewPwd: 'New Password (optional)',
    setPlaceholderNewPwd: 'Enter your new password',
    setForgotPwd: 'Forgot your old password? (Send reminder)',
    setLanguageTitle: 'Language Selection / Nyelvválasztás / Sprache',
    setLanguageDesc: 'Select system language (Nyelvválasztás / Sprache wählen):',
    setAvatarDesc: 'Change profile picture with the bottom-left button, or delete with the bottom-right button.',
    setSuccessAll: 'Profile data and password saved successfully!',
    setSuccessPwd: 'Password changed successfully!',
    setSuccessProfile: 'Profile data saved successfully!',
    setSuccessGeneral: 'Changes saved successfully!',
    setErrorName: 'Name is required!',
    setErrorPwdMatch: 'Both old and new password fields are required to change your password!',
    setErrorPwdLength: 'New password must be at least 6 characters long!',
    setDbAdminInfo: 'Database Admin Info',
    setDbRefresh: 'Refresh',
    setDbStorageUsed: 'Total storage used:',
    setDbMovements: 'Inventory Movements',
    setDbMovementsUnit: 'transactions',
    setDbMaterials: 'Materials',
    setDbMaterialsUnit: 'items',
    setDbAccounts: 'Accounts',
    setDbAccountsUnit: 'users',
    setDbFetching: 'Fetching sizes...',

    statAddedPast7Days: 'in the last 7 days',
    statNoAddedPast7Days: 'No new items in the last 7 days',
    statCriticalRed: 'critical stock level (<40%)',
    statStockOptimal: 'All stock levels optimal',
    statComparedToYesterday: 'compared to yesterday',
    statUnchangedYesterday: 'Unchanged compared to yesterday',

    // Allowed Emails View
    allowedTitle: 'Allowed Emails',
    allowedSubtitle: 'E-mail addresses authorized to register and sign in to the warehouse app (Manager panel).',
    allowedCsvExport: 'CSV Export',
    allowedBtnAdd: 'Add Allowed Email',
    allowedTotalCount: 'Total {count} allowed email addresses.',
    allowedSearchPlaceholder: 'Search by name or email...',
    allowedLoading: 'Loading...',
    allowedColName: 'NAME / NOTE',
    allowedColEmail: 'ALLOWED EMAIL ADDRESS',
    allowedColDate: 'ALLOWED DATE',
    allowedColStatus: 'STATUS',
    allowedColActions: 'ACTIONS',
    allowedSelfBadge: '(Self account)',
    allowedDefaultUser: 'Authorized User',
    allowedStatusActive: 'Allowed',
    allowedBtnRevoke: 'Revoke',
    allowedRevokeTitle: 'Revoke permission',
    allowedRevokeSelfError: 'You cannot revoke permission for your own account for security reasons!',
    allowedRevokeConfirm: 'Are you sure you want to revoke permission for {email}?',
    allowedNoResults: 'No allowed email addresses found matching the search criteria.',
    allowedModalTitle: 'Authorize New Email',
    allowedModalDesc: 'Enter the email address to authorize. The user will be able to register and sign in to SmartFarm using this email.',
    allowedModalLabelEmail: 'Email address *',
    allowedModalLabelName: 'Name / Note (Optional)',
    allowedModalPlaceholderEmail: 'worker@company.com',
    allowedModalPlaceholderName: 'e.g. John Doe (Operator)',
    allowedModalBtnCancel: 'Cancel',
    allowedModalBtnSubmit: 'Authorize',
    allowedModalBtnLoading: 'Adding...',
    allowedModalErrorEmailRequired: 'Please enter an email address!',

    // Login View
    loginTitle: 'Sign in to the system',
    loginCardTitle: 'Sign In',
    loginCardSubtitle: 'Sign in to the SmartFarm warehouse management system',
    loginLabelEmail: 'Email Address',
    loginPlaceholderEmail: 'user@example.com',
    loginLabelPwd: 'Password',
    loginPlaceholderPwd: '••••••••••••',
    loginBtnSubmit: 'Sign In',
    loginBtnSubmitLoading: 'Signing in...',
    loginRemember: 'Remember me',
    loginForgotPwdLink: 'Forgot password?',
    loginOrDivider: 'or',
    loginNoAccount: "Don't have an account? Sign Up",
    loginHaveAccount: 'Already have an account? Sign In',

    loginRegisterTitle: 'Sign Up',
    loginRegisterCardTitle: 'Sign Up',
    loginRegisterCardSubtitle: 'Create a new SmartFarm account',
    loginBtnRegister: 'Sign Up',
    loginRegisterBtnSubmit: 'Register',
    loginRegisterBtnSubmitLoading: 'Registering...',
    loginRoleAdmin: 'Warehouse Manager (Admin)',
    loginRoleOperator: 'Warehouse Worker (Operator)',
    loginLabelFullName: 'Full Name',
    loginRegisterPlaceholderName: 'John Doe',
    loginLabelRole: 'Role',

    loginForgotCardTitle: 'Forgot Password',
    loginForgotCardSubtitle: 'Enter your email address to receive a password reset link',
    loginForgotBtnSubmit: 'Send Reset Link',
    loginForgotBtnSubmitLoading: 'Sending...',
    loginForgotBackToLogin: 'Back to Sign In',

    loginResetCardTitle: 'Set New Password',
    loginResetCardSubtitle: 'Enter a new password for your account',
    loginResetLabelNewPwd: 'New Password',
    loginResetLabelConfirmPwd: 'Confirm New Password',
    loginResetBtnSubmit: 'Update Password',
    loginResetBtnSubmitLoading: 'Updating...',

    authErrorEmailRequired: 'Please enter your email address!',
    authErrorPwdRequired: 'Please enter your password!',
    authErrorNameRequired: 'Please enter your full name!',
    authErrorNewPwdRequired: 'Please enter your new password!',
    authErrorPwdMismatch: 'Passwords do not match!',
    authErrorNotAllowed: 'This email address is not authorized in SmartFarm! Please contact your warehouse manager for authorization.',
    authErrorInvalidCredentials: 'Invalid email address or password. Please check your credentials!',
    authErrorEmailNotConfirmed: 'Email address not verified yet! Please check your inbox for the confirmation link.',
    authErrorUserExists: 'An account with this email address already exists!',
    authErrorPwdWeak: 'New password must be at least 6 characters long!',
    authErrorRateLimit: 'Too many requests in a short time! Please wait a moment and try again.',
    authErrorInvalidToken: 'The password reset link is invalid or has expired.',
    authErrorGeneral: 'An error occurred. Please try again!',
    authErrorNotRegistered: 'This email address is not registered in the system!',

    authSuccessRegister: 'Registration successful! Please check your email for the confirmation link.',
    authSuccessRegisterDemo: 'Registration successful in offline mode! You can now log in.',
    authSuccessForgotSent: 'Password reset link sent to your email address! Please check your inbox.',
    authSuccessForgotDemo: 'Offline mode: Email delivery simulated. Verification successful! Enter your new password.',
    authSuccessResetDone: 'Password successfully updated! Please log in with your new password.',
    authSuccessResetDemo: 'Offline mode: Password successfully updated! You can now log in with your new password.',
  },
  de: {
    // Sidebar & Navigation
    appName: 'SmartFarm Inventar',
    version: 'Version 1.2.0',
    navDashboard: 'Dashboard',
    navMaterials: 'Materialien',
    navNewMaterial: 'Neues Material',
    navMovements: 'Bewegungen',
    navQrCodes: 'QR-Codes',
    navUsers: 'Benutzer',
    navAllowedEmails: 'Genehmigte E-Mails',
    navSettings: 'Einstellungen',
    navLogout: 'Abmelden',

    // Header & General UI
    roleAdmin: 'Lagerleiter',
    roleOperator: 'Lagermitarbeiter',
    roleKezelo: 'Bediener',
    notifTitle: 'Neueste Lagerbewegungen',
    notifEmpty: 'Bisher wurden keine Lagerbewegungen aufgezeichnet.',
    notifAll: 'Alle Bewegungen anzeigen',
    notifAriaLabel: 'Benachrichtigungen',
    toastTitle: 'Lagerbewegung stattgefunden!',
    searchPlaceholder: 'Suche nach Material, Code oder Ort...',
    searchResultsTitle: 'Suchergebnisse',
    noSearchResults: 'Keine passenden Materialien gefunden.',
    pressEnterToView: 'Drücken Sie ENTER zum Anzeigen',
    qrScanBtn: 'QR scannen',
    demoNotice: 'Das System läuft derzeit im Offline-Demo- / LocalStorage-Modus.',
    demoLink: 'Supabase-Verbindungseinstellungen konfigurieren',
    loading: 'Laden...',
    save: 'Speichern',
    saveData: 'Daten speichern',
    saving: 'Speichern...',
    savingData: 'Daten werden gespeichert...',
    cancel: 'Abbrechen',
    btnExportCSV: 'CSV Export',

    // Dashboard Overview
    dbTitle: 'Dashboard-Übersicht',
    dbSubtitle: 'Übersicht über den Lagerbestand und wichtige Kennzahlen.',
    cardTotalMaterials: 'Materialien Gesamt',
    cardLowStock: 'Niedriger Bestand',
    cardTodayMovements: 'Heutige Bewegungen',
    levelGreen: 'Grüner Bereich (>70%)',
    levelYellow: 'Gelber Bereich (40-70%)',
    levelRed: 'Roter Bereich (<40%)',
    criticalStockTitle: 'Kritische Lagerbestände',
    viewAllCritical: 'Alle kritischen Materialien anzeigen',
    categoryDistribution: 'Kategorieverteilung',
    totalText: 'GESAMT',
    statStatus: 'STATUS',
    statId: 'ID',
    statName: 'NAME',
    statStock: 'BESTAND',
    statMax: 'MAX',
    statLevel: 'BEREICH',
    statLocation: 'ORT',
    comparedToLastWeek: 'im Vergleich zur Vorwoche',
    comparedToYesterday: 'im Vergleich zu gestern',
    dbConsumptionTitle: 'Monatlicher Verbrauchstrend',
    dbForecastTitle: 'Intelligente Bestandsprognose',
    dbForecastStable: 'Alle Bestände stabil basierend auf der aktuellen Nutzung.',
    dbForecastRisk: 'Kritische Reichweite',
    dbForecastDaysLeft: 'Tage Reichweite übrig',
    dbForecastReorder: 'Empfohlene Nachbestellung',
    dbDemoDataNotice: 'Demodaten werden angezeigt (noch keine Buchungen vorhanden)',

    // Materials View
    matTitle: 'Lagerbestand',
    matSubtitle: 'Liste aller registrierten Materialien und ihrer aktuellen Bestände.',
    matCategories: 'Kategorien:',
    matAll: 'Alle',
    matSearch: 'Suchen...',
    matNoResults: 'Keine Materialien gefunden, die den Kriterien entsprechen.',
    matCardView: 'Kartenansicht',
    matTableView: 'Tabellenansicht',
    matActions: 'Aktionen',
    matEdit: 'Bearbeiten',
    matDelete: 'Löschen',
    matIntake: 'Einlagern',
    matCheckout: 'Auslagern',
    matPrint: 'Drucken',
    matDeactivate: 'Deaktivieren',
    matRestore: 'Wiederherstellen',
    matActiveTab: 'Aktive Materialien',
    matInactiveTab: 'Inaktive Materialien / Archiv',
    matDeactivateConfirm: 'Sind Sie sicher, dass Sie {name} deaktivieren möchten? Ein- und Auslagerungen werden blockiert.',
    matDeactivateTitle: 'Material deaktivieren',
    matDeactivateWarning: 'Im inaktiven Zustand kann das Material nicht ein- oder ausgelagert werden, und das Scannen des QR-Codes wird blockiert.',
    matDeactivateBtn: 'Deaktivierung bestätigen',
    matRestoreConfirm: 'Sind Sie sicher, dass Sie {name} wieder in den aktiven Bestand aufnehmen möchten?',
    matRestoreTitle: 'Material wiederherstellen',
    matRestoreWarning: 'Nach der Wiederherstellung kann das Material wieder ein- und ausgelagert werden, und das Scannen des QR-Codes funktioniert normal.',
    matRestoreBtn: 'Wiederherstellung bestätigen',
    matErrorInactiveScan: 'Warnung! Das Material "{name}" ({id}) ist derzeit inaktiv. Buchungen sind nicht erlaubt!',
    matErrorGepScan: 'Dieses Produkt ist GEP und Sie haben keine Berechtigung dafür!',
    matGepNoPermissionTitle: 'Keine Berechtigung',
    matGepNoPermissionBody: 'Das Produkt "{name}" ({id}) ist GEP und Sie haben keine Berechtigung dafür!',
    ok: 'OK',

    // Movements View
    movTitle: 'Lagerbewegungsprotokoll',
    movSubtitle: 'Chronologische Liste der Ein- und Auslagerungen im Lager.',
    movNoResults: 'Bisher wurden keine Lagerbewegungen aufgezeichnet.',
    movColType: 'TYP',
    movColMaterial: 'MATERIAL',
    movColQty: 'MENGE',
    movColDate: 'DATUM',
    movColUser: 'BENUTZER',
    movColNotes: 'NOTIZ',
    movTypeIntake: 'Eingang',
    movTypeCheckout: 'Ausgang',

    // QR Codes View
    qrTitle: 'QR-Code-Generator',
    qrSubtitle: 'Generieren und drucken Sie QR-Codes für Materialien, um sie einfach zu identifizieren.',
    qrColAction: 'Drucken',
    qrDeselectAll: 'Auswahl aufheben',
    qrSelectAll: 'Alle auswählen',
    qrPrintSelected: 'Ausgewählte drucken ({count} Stk.)',
    qrSearchPlaceholder: 'Suche nach Name, ID oder Ort...',
    qrSelectedCounter: 'Ausgewählt: {selected} / {total} Materialien',
    qrNoMatchingMaterials: 'Keine Materialien entsprechen den Suchkriterien.',
    qrSinglePrintTitle: 'Einzelnen QR-Code drucken',
    qrNoLocation: 'Nicht angegeben',
    qrPrintDocumentTitle: 'SmartFarm - A4 QR-Code Druck ({count} Stk.)',
    qrScanTitle: 'QR-Code scannen',
    qrClose: 'Schließen',
    qrCameraLabel: 'Kamera:',
    qrCameraFallback: 'Kamera',
    qrManualLabel: 'Material-ID (z. B. PRM-001)',
    qrManualBtn: 'ID abrufen',
    qrBackToCamera: 'Zurück zur Kamera',
    qrTypeManual: 'Code manuell eingeben',
    qrErrorNoCamera: 'Keine Kamera gefunden. Bitte verwenden Sie die manuelle Codeeingabe.',
    qrErrorSecureContext: 'Fehler beim Kamerazugriff: Browser erlauben den Kamerazugriff aus Sicherheitsgründen nur über sichere Verbindungen (HTTPS oder localhost). Verwenden Sie HTTPS (z. B. localtunnel/ngrok) oder manuelle Eingabe!',
    qrErrorScanFailed: 'Fehler bei der Kamerasuche. Sie können die manuelle Eingabe verwenden.',
    qrErrorCameraStart: 'Kamera konnte nicht gestartet werden. Bitte erteilen Sie die Zugriffsberechtigung in Ihrem Browser.',
    colCategory: 'Kategorie',
    colUnit: 'Einheit',
    unitDb: 'Stk.',
    cat_Herbicit: 'Herbizid',
    cat_Insecticit: 'Insektizid',
    cat_Fungicit: 'Fungizid',
    cat_Biostimulátor: 'Biostimulanz',
    cat_Permetszerek: 'Pflanzenschutzmittel',
    cat_Műtrágyák: 'Düngemittel',
    'cat_Szilárd műtrágya': 'Fester Dünger',
    'cat_Folyékony műtrágya': 'Flüssigdünger',
    cat_MűtrágyaMind: 'Alle Düngemittel',
    cat_MutragyaTipus: 'Düngerzustand:',
    cat_MutragyaSzilard: 'Fest (kg / t)',
    cat_MutragyaFolyekony: 'Flüssig (l)',
    cat_Vetőmagok: 'Saatgut',
    cat_Tápok: 'Futtermittel',
    cat_Adalékanyagok: 'Zusatzstoffe',
    cat_Egyéb: 'Sonstiges',
    txLocationLabel: 'Ort',
    txCurrentStock: 'Aktueller Bestand',
    txTitleAdjustment: 'Bestandsänderung',
    txErrorFailed: 'Buchung fehlgeschlagen.',
    txErrorMaxCapacity: 'Mit der hinzugefügten Menge ({total} {unit}) würde der Bestand die maximale Kapazität ({max} {unit}) überschreiten! Bitte erhöhen Sie die maximale Kapazität in den Materialeinstellungen.',
    txErrorNotEnoughStock: 'Nicht genügend Bestand! Derzeit verfügbar: {current} {unit}',
    txTypeLabel: 'Vorgangsart',
    txOptCheckout: 'Ausgang (Entnahme)',
    txOptIntake: 'Eingang (Befüllung)',
    txQtyLabel: 'Menge',
    txNotesLabel: 'Notiz (optional)',
    txNotesPlaceholder: 'z. B. Für tägliches Spritzen, Bestellung eingetroffen...',
    txBtnSubmit: 'Buchen',
    mfLabelExpiration: 'Ablaufdatum (optional)',
    matExpiration: 'Ablaufdatum',
    matExpired: 'ABGELAUFEN!',
    matExpiringSoon: 'Läuft bald ab',
    matNoExpiration: 'Nicht angegeben',
    dbExpiringAlert: 'Haltbarkeitswarnungen',
    mfEditTitle: 'Material bearbeiten',
    mfNewTitle: 'Neues Material hinzufügen',
    mfErrorCamera: 'Kamerazugriff fehlgeschlagen. Überprüfen Sie die Browser-Berechtigungen.',
    mfErrorFormat: 'Die ID muss im Format AAA-111 vorliegen (z. B. PRM-001)!',
    mfErrorExists: 'Material mit dieser ID existiert bereits: ',
    mfErrorQtyPositive: 'Mengen müssen größer als 0 sein.',
    mfErrorQtyMax: 'Der aktuelle Bestand darf nicht größer als die maximale Kapazität sein.',
    mfErrorSave: 'Fehler beim Speichern des Materials.',
    mfErrorGepRequired: 'Bitte wählen Sie den GEP-Feldwert aus!',
    mfLabelId: 'Kennung (ID)',
    mfPlaceholderId: 'z. B. PRM-001',
    mfLabelName: 'Materialname',
    mfPlaceholderName: 'z. B. Pflanzenschutzmittel A',
    mfLabelStartQty: 'Anfangsbestand',
    mfLabelMaxCap: 'Maximale Kapazität',
    mfUnitPcs: 'Stück (Stk.)',
    mfUnitKg: 'Kilogramm (kg)',
    mfUnitL: 'Liter (l)',
    mfLabelLoc: 'Lagerplatz (Sektion-Abteilung-Regal)',
    mfPlaceholderLoc: 'z. B. A1-01-03',
    mfLabelImage: 'Produktbild aufnehmen oder hochladen',
    mfBtnCapture: 'Foto aufnehmen',
    mfBtnCancelCapture: 'Fotoaufnahme abbrechen',
    mfAltPreview: 'Produktvorschau',
    mfBtnChangeImage: 'Bild ändern',
    mfBtnDeleteImage: 'Bild löschen',
    mfBtnTakePhoto: 'Foto machen',
    mfBtnUploadPhoto: 'Bild hochladen',
    mfBtnSaveNew: 'Produkt speichern',
    mfBtnSaveEdit: 'Änderungen speichern',

    // Users View
    usrTitle: 'Benutzerverwaltung',
    usrSubtitle: 'Lagermitarbeiter und Berechtigungen für den Systemzugriff.',
    usrColName: 'NAME',
    usrColEmail: 'E-MAIL',
    usrColRole: 'ROLLE',
    usrRoleAdmin: 'Lagerleiter (Admin)',
    usrRoleOperator: 'Lagermitarbeiter (Bediener)',
    usrStatusActive: 'Aktiv',
    usrNoUsers: 'Keine Benutzer gefunden.',

    // Settings View
    setProfileTitle: 'Profileinstellungen',
    setLabelName: 'Name',
    setPlaceholderName: 'Vollständiger Name',
    setLabelEmail: 'E-Mail-Adresse (schreibgeschützt)',
    setLabelRole: 'Rolle (administrativ)',
    setLabelOldPwd: 'Altes Passwort (optional)',
    setPlaceholderOldPwd: 'Geben Sie Ihr aktuelles Passwort ein',
    setLabelNewPwd: 'Neues Passwort (optional)',
    setPlaceholderNewPwd: 'Geben Sie Ihr neues Passwort ein',
    setForgotPwd: 'Altes Passwort vergessen? (Erinnerung senden)',
    setLanguageTitle: 'Sprachauswahl / Nyelvválasztás / Language',
    setLanguageDesc: 'Wählen Sie die Systemspache (Nyelvválasztás / Language select):',
    setAvatarDesc: 'Ändern Sie das Profilbild mit der Taste unten links, oder löschen Sie es mit der Taste unten rechts.',
    setSuccessAll: 'Profildaten und Passwort erfolgreich gespeichert!',
    setSuccessPwd: 'Passwort erfolgreich geändert!',
    setSuccessProfile: 'Profildaten erfolgreich gespeichert!',
    setSuccessGeneral: 'Änderungen erfolgreich gespeichert!',
    setErrorName: 'Name ist erforderlich!',
    setErrorPwdMatch: 'Sowohl das alte als auch das neue Passwort müssen angegeben werden!',
    setErrorPwdLength: 'Das neue Passwort muss mindestens 6 Zeichen lang sein!',
    setDbAdminInfo: 'Datenbank-Administrator-Info',
    setDbRefresh: 'Aktualisieren',
    setDbStorageUsed: 'Gesamter genutzter Speicher:',
    setDbMovements: 'Lagerbewegungen',
    setDbMovementsUnit: 'Transaktionen',
    setDbMaterials: 'Materialien',
    setDbMaterialsUnit: 'Artikel',
    setDbAccounts: 'Konten',
    setDbAccountsUnit: 'Benutzer',
    setDbFetching: 'Größen werden abgerufen...',

    statAddedPast7Days: 'in den letzten 7 Tagen',
    statNoAddedPast7Days: 'Keine neuen Artikel in den letzten 7 Tagen',
    statCriticalRed: 'kritischer Bestand (<40%)',
    statStockOptimal: 'Alle Lagerbestände optimal',
    statComparedToYesterday: 'im Vergleich zu gestern',
    statUnchangedYesterday: 'Unverändert im Vergleich zu gestern',

    // Allowed Emails View
    allowedTitle: 'Genehmigte E-Mails',
    allowedSubtitle: 'E-Mail-Adressen, die zur Registrierung und Anmeldung in der Lager-App berechtigt sind (Verwalterbereich).',
    allowedCsvExport: 'CSV-Export',
    allowedBtnAdd: 'Neue E-Mail genehmigen',
    allowedTotalCount: 'Insgesamt {count} genehmigte E-Mail-Adressen.',
    allowedSearchPlaceholder: 'Suche nach Name oder E-Mail...',
    allowedLoading: 'Laden...',
    allowedColName: 'NAME / HINWEIS',
    allowedColEmail: 'GENEHMIGTE E-MAIL-ADRESSE',
    allowedColDate: 'GENEHMIGT AM',
    allowedColStatus: 'STATUS',
    allowedColActions: 'AKTIONEN',
    allowedSelfBadge: '(Eigenes Konto)',
    allowedDefaultUser: 'Berechtigter Benutzer',
    allowedStatusActive: 'Genehmigt',
    allowedBtnRevoke: 'Widerrufen',
    allowedRevokeTitle: 'Berechtigung widerrufen',
    allowedRevokeSelfError: 'Sie können die Berechtigung für Ihr eigenes Konto aus Sicherheitsgründen nicht widerrufen!',
    allowedRevokeConfirm: 'Möchten Sie die Berechtigung für {email} wirklich widerrufen?',
    allowedNoResults: 'Keine genehmigten E-Mail-Adressen gefunden, die den Suchkriterien entsprechen.',
    allowedModalTitle: 'Neue E-Mail genehmigen',
    allowedModalDesc: 'Geben Sie die zu genehmigende E-Mail-Adresse ein. Der Benutzer kann sich mit dieser E-Mail registrieren und anmelden.',
    allowedModalLabelEmail: 'E-Mail-Adresse *',
    allowedModalLabelName: 'Name / Hinweis (Optional)',
    allowedModalPlaceholderEmail: 'mitarbeiter@firma.de',
    allowedModalPlaceholderName: 'z.B. Max Mustermann (Bediener)',
    allowedModalBtnCancel: 'Abbrechen',
    allowedModalBtnSubmit: 'Genehmigen',
    allowedModalBtnLoading: 'Hinzufügen...',
    allowedModalErrorEmailRequired: 'Bitte geben Sie eine E-Mail-Adresse ein!',

    // Login View
    loginTitle: 'Am System anmelden',
    loginCardTitle: 'Anmeldung',
    loginCardSubtitle: 'Melden Sie sich im SmartFarm Lagerverwaltungssystem an',
    loginLabelEmail: 'E-Mail-Adresse',
    loginPlaceholderEmail: 'beispiel@firma.de',
    loginLabelPwd: 'Passwort',
    loginPlaceholderPwd: '••••••••••••',
    loginBtnSubmit: 'Anmelden',
    loginBtnSubmitLoading: 'Anmeldung...',
    loginRemember: 'Angemeldet bleiben',
    loginForgotPwdLink: 'Passwort vergessen?',
    loginOrDivider: 'oder',
    loginNoAccount: 'Noch kein Konto? Registrieren',
    loginHaveAccount: 'Bereits ein Konto? Anmelden',

    loginRegisterTitle: 'Registrieren',
    loginRegisterCardTitle: 'Registrierung',
    loginRegisterCardSubtitle: 'Erstellen Sie ein neues SmartFarm-Konto',
    loginBtnRegister: 'Registrieren',
    loginRegisterBtnSubmit: 'Registrieren',
    loginRegisterBtnSubmitLoading: 'Registrierung...',
    loginRoleAdmin: 'Lagerleiter (Admin)',
    loginRoleOperator: 'Lagermitarbeiter (Bediener)',
    loginLabelFullName: 'Vollständiger Name',
    loginRegisterPlaceholderName: 'Max Mustermann',
    loginLabelRole: 'Rolle',

    loginForgotCardTitle: 'Passwort vergessen',
    loginForgotCardSubtitle: 'Geben Sie Ihre E-Mail-Adresse ein, um einen Link zum Zurücksetzen des Passworts zu erhalten',
    loginForgotBtnSubmit: 'Link zum Zurücksetzen senden',
    loginForgotBtnSubmitLoading: 'Senden...',
    loginForgotBackToLogin: 'Zurück zur Anmeldung',

    loginResetCardTitle: 'Neues Passwort festlegen',
    loginResetCardSubtitle: 'Geben Sie ein neues Passwort für Ihr Konto ein',
    loginResetLabelNewPwd: 'Neues Passwort',
    loginResetLabelConfirmPwd: 'Neues Passwort bestätigen',
    loginResetBtnSubmit: 'Passwort aktualisieren',
    loginResetBtnSubmitLoading: 'Aktualisieren...',

    authErrorEmailRequired: 'Bitte geben Sie Ihre E-Mail-Adresse ein!',
    authErrorPwdRequired: 'Bitte geben Sie Ihr Passwort ein!',
    authErrorNameRequired: 'Bitte geben Sie Ihren vollständigen Namen ein!',
    authErrorNewPwdRequired: 'Bitte geben Sie Ihr neues Passwort ein!',
    authErrorPwdMismatch: 'Die Passwörter stimmen nicht überein!',
    authErrorNotAllowed: 'Diese E-Mail-Adresse ist in SmartFarm nicht berechtigt! Bitte kontaktieren Sie Ihren Lagerleiter.',
    authErrorInvalidCredentials: 'Ungültige E-Mail-Adresse oder Passwort. Bitte überprüfen Sie Ihre Eingaben!',
    authErrorEmailNotConfirmed: 'E-Mail-Adresse noch nicht bestätigt! Bitte prüfen Sie Ihren Posteingang.',
    authErrorUserExists: 'Ein Konto mit dieser E-Mail-Adresse existiert bereits!',
    authErrorPwdWeak: 'Das neue Passwort muss mindestens 6 Zeichen lang sein!',
    authErrorRateLimit: 'Zu viele Versuche in kurzer Zeit! Bitte warten Sie kurz und versuchen Sie es erneut.',
    authErrorInvalidToken: 'Der Link zum Zurücksetzen des Passworts ist ungültig oder abgelaufen.',
    authErrorGeneral: 'Ein Fehler ist aufgetreten. Bitte versuchen Sie es erneut!',
    authErrorNotRegistered: 'Diese E-Mail-Adresse ist im System nicht registriert!',

    authSuccessRegister: 'Registrierung erfolgreich! Bitte prüfen Sie Ihre E-Mails für den Bestätigungslink.',
    authSuccessRegisterDemo: 'Registrierung im Offline-Modus erfolgreich! Sie können sich jetzt anmelden.',
    authSuccessForgotSent: 'Link zum Zurücksetzen des Passworts an Ihre E-Mail gesendet! Bitte prüfen Sie Ihren Posteingang.',
    authSuccessForgotDemo: 'Offline-Modus: E-Mail-Versand simuliert. Identifizierung erfolgreich! Geben Sie Ihr neues Passwort ein.',
    authSuccessResetDone: 'Passwort erfolgreich geändert! Bitte melden Sie sich mit Ihrem neuen Passwort an.',
    authSuccessResetDemo: 'Offline-Modus: Passwort erfolgreich geändert! Sie können sich jetzt mit dem meuen Passwort anmelden.',
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem('smartfarm_language') as Language) || 'hu';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('smartfarm_language', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || translations['hu'][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useTranslation = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useTranslation must be used within a LanguageProvider');
  }
  return context;
};
