import React, { useState, useEffect, useRef } from 'react';
import { Search, Plus, Check, ChevronDown, X } from 'lucide-react';

interface ActiveIngredientsSelectProps {
  selectedIngredients: string[];
  onChange: (ingredients: string[]) => void;
}

const PREDEFINED_INGREDIENTS = [
  '(E)-12-tetradecenil-acetát',
  '(E)-5-decén-1-il-acetát',
  '(E)-5-decén-1-ol',
  '(E)7-(Z)9 dodekadienil acetát',
  '(E,E)-8,10-dodekadién-1-ol',
  '(E,Z)-3,8-tetradecadien-1-il-acetát',
  '(E,Z)-7,9-dodecadién-1-il-acetát',
  '(E,Z,Z)-3,8,11-Tetradekatrién-1-il acetát',
  '(Z)- és (E)-11-izomer',
  '(Z)-11-hexadekanal',
  '(Z)-11-tetradecén-1-il-acetát',
  '(Z)-12-tetradecenil-acetát',
  '(Z)-8-dodecén-1-il-acetát',
  '(Z)-8-dodecén-1-ol',
  '(Z)-9-dodecén-1-il-acetát',
  '(Z)-9-hexadekanal',
  '(Z)-9-tetradecén-1-il-acetát',
  '1-Dekanol',
  '1-metilciklopropén',
  '1-metoxi-2-propanol',
  '1-naftilacetamid (1-NAD)',
  '1-naftil-ecetsav (1-NAA)',
  '2,4-D',
  '2-etil-1-hexanol',
  '2-etil-hexanol EO-PO nemionos felületaktív anyag',
  '3 növény 33%-os etil-alkoholos kivonata',
  '3-piridil-etil-nikotinát',
  '6-benziladenin',
  '8-hidroxi-kinolin',
  'Abamektin',
  'ABE-IT 56',
  'acekinocil',
  'Acetamiprid',
  'acetoklór',
  'aceton',
  'acibenzolár-S-metil',
  'AD-67',
  'Adalia bipuctata',
  'Akanthomyces muscarius Ve6 törzs',
  'Aklonifen',
  'Akril észter kopolimerek vizes oldata',
  'Akril gyanta',
  'akril kopolimer',
  'Akrilát emulzió',
  'akrilsav-észter-sztirol',
  'Alfa-cipermetrin (alfametrin)',
  'alkilfenol alkoxilát',
  'alkilfenol polioxietilén',
  'alkilpoliglukozid citrát',
  'alkohol alkoxilát',
  'alkohol-etoxilát',
  'Alkoholok és szulfonált zsírsavak és dietilén-glikol-abietate kén-észterei',
  'Aluminium ammónium szulfát',
  'Aluminium-foszfid',
  'Aluminium-szilikát (kaolin)',
  'Amblydromalus limonicus',
  'Amblyseius andersoni',
  'Amblyseius californicus',
  'Amblyseius cucumeris',
  'Amblyseius degenerans',
  'Amblyseius montdorensis',
  'Amblyseius swirskii',
  'ametoktradin',
  'Amidoszulfuron',
  'Aminopiralid',
  'amiszulbrom',
  'Amitrol',
  'ammónium propionát',
  'Ammónium-acetát',
  'ammónium-szulfát',
  'Anagyrus vladimiri',
  'Androlaelaps casalis',
  'antivad',
  'Aphelinus abdominalis',
  'Aphidius colemani',
  'Aphidius ervi',
  'Aphidius matricariae',
  'Aphidoletes aphidimyza',
  'Ásványi anyagok',
  'ásványiolaj gyanta',
  'Attapulgite ásvány',
  'Aureobasidium Pullulans',
  'Avokádó olaj',
  'azadiraktin',
  'Azimszulfuron',
  'Azoxistrobin',
  'Bacillus amyloliquefaciens FZB24 törzs',
  'Bacillus amyloliquefaciens MBI 600',
  'Bacillus amyloliquefaciens subsp. plantarum D747',
  'Bacillus subtilis QST 713 törzs',
  'Bacillus thuringiensis ssp. israeliensis',
  'Bacillus thuringiensis ssp. kurstaki',
  'Bacillus thuringiensis ssp. Tenebrionis',
  'Bacillus thuringiensis subsp. Aizawai ABTS-1857 és GC-91 törzs',
  'bálványfa és aranyvessző keverék 33 %-os etil-alkoholos kivonata',
  'Beauveria bassiana',
  'Beflubutamid',
  'Benalaxil',
  'Benalaxil-M',
  'Benfluralin',
  'Benszulfuron',
  'Bentazon',
  'Bentiavalikarb',
  'Benzoesav',
  'benzovindiflupir',
  'Béta-ciflutrin',
  'béta-pinén oligomerizált terméke',
  'Bifenazát',
  'Bifenox',
  'Bifentrin',
  'Bispyribac',
  'bixafen',
  'Bombus terrestris',
  'Bordói keverék',
  'Boszkalid',
  'Bromoxinil',
  'bromukonazol',
  'bupirimát',
  'butilakrilát-sztirol kopolimer',
  'C7–C18 zsírsavak és C18 telítetlen káliumsók',
  'C7–C20 zsírsavak',
  'Candida oleophila O törzs',
  'Carpoglyphus lactis',
  'Cerevisane',
  'Cheyletus eruditus',
  'ciántraniliprol',
  'ciazofamid',
  'Ciflufenamid',
  'cikloxidim',
  'Cimoxanil',
  'Cinidon-etil',
  'Cink-foszfid',
  'Cipermetrin',
  'Ciprodinil',
  'ciprokonazol',
  'ciproszulfamid',
  'citrál',
  'citrom olaj',
  'citromsav',
  'Clonostachys rosea J1446',
  'Coccidoxenoides perminutus',
  'Coniothyrium minitans',
  'COS-OGA',
  'Cryptolaemus montrouzieri',
  'Cydia pomonella Granulovirus (CpGV)',
  'Dacnusa sibirica',
  'Daminozid',
  'dazomet',
  'Delphastus catalinae',
  'Deltametrin',
  'denatónium-benzoát',
  'denaturált szesz',
  'dendrocol 17 SK',
  'Dezmedifam',
  'di-1-p-mentén',
  'Difenokonazol',
  'Diflubenzuron',
  'Diflufenikán',
  'Diglyphus isaea',
  'Dikamba',
  'diklórmid',
  'diklórprop-P',
  'dikvát (dibromid)',
  'Dimetaklór',
  'Dimetenamid-P',
  'dimetil-polisziloxán',
  'Dimetoát',
  'Dimetomorf',
  'Dimoxistrobin',
  'dinátrium-alkilpoliglükóz-citrát',
  'Dinátrium-foszfonát',
  'Dinokap',
  'Dispers Red 38-5507',
  'ditianon',
  'Dodekán-1-ol',
  'dodin',
  'Ecetsav',
  'egyéb feromon',
  'emamektin benzoát',
  'Encarsia formosa',
  'Ephedrus cerasicola',
  'Ephestia kuehniella',
  'Epoxikonazol',
  'Eretmocerus eremicus',
  'Eszfenvalerát',
  'Etametszulfuron-metil',
  'etanol (etil-alkohol)',
  'Etefon',
  'etilan TT-15',
  'Etilén',
  'etil-merkaptán',
  'Etofenprox',
  'Etofumezát',
  'Etoxazol',
  'etoxilált alkohol',
  'Etoxilált alkoholok C9-11-izo, C10-ben gazdag',
  'etoxilált alkoholok keveréke',
  'etoxilált izodecil alkohol',
  'etoxilált izotridekanol',
  'etoxilált montánsav',
  'etoxilált oktilfenol',
  'etoxilált repceolaj',
  'etoxilált ricinus olaj',
  'etoxilált zsíralkohol',
  'etoxilált zsíramin',
  'eugenol',
  'faggyú',
  'fakátrány',
  'Famoxadon',
  'fehér olaj',
  'Fehér virágú édes csillagfürt (Lupinus albus) csíráztatott magjából nyert vizes kivonat',
  'fehérje-cink komplex',
  'Fenamidon',
  'Fenamifosz',
  'fenarimol',
  'fenazaquin',
  'fenbutatin-oxid',
  'Fenhexamid',
  'fenmedifám',
  'Fenoxaprop-P',
  'fenoxikarb',
  'fenpikoxamid',
  'fenpirazamin',
  'Fenpiroximát',
  'Fenpropidin',
  'Fenpropimorf',
  'fenyőolaj',
  'feromon',
  'Fipronil',
  'Flazaszulfuron',
  'Flonikamid (IKI-220)',
  'Floraszulam',
  'Florpirauxifen benzil',
  'Fluazifop-P',
  'Fluazinam',
  'Fludioxonil',
  'Flufenacet',
  'flufenoxuron',
  'flufenzin (diflovidazin)',
  'Flumioxazin',
  'fluopikolid',
  'fluopiram',
  'Fluoxastrobin',
  'flupiradifuron',
  'fluquinkonazol',
  'flurokloridon',
  'Fluroxipir',
  'Flutianil',
  'Flutolanil',
  'flutriafol',
  'fluxapiroxad',
  'fluxofenim',
  'Fluzilazol',
  'fodormentaolaj',
  'Fokhagymakivonat',
  'Folpet',
  'foramszulfuron',
  'Forklórfenuron',
  'Foszetil',
  'foszmet',
  'Fosztiazát',
  'földi poszméh',
  'furilazol',
  'fürkészdarazsak',
  'Gamma-cihalotrin',
  'geraniol',
  'Gibberellinek',
  'gibberellinsav',
  'glicerin',
  'glifozát',
  'Glufozinát',
  'guazatin',
  'gyanta',
  'halauxifen-metil',
  'haloxifop-P (haloxifop-P)',
  'Hárombázisú réz-szulfát',
  'Helicoverpa armigera sejtmag-poliéder-vírus',
  'heptametiltrisziloxánnal mód. polialkilénoxid',
  'Heterorhabditis bacteriophora (EN01)',
  'hexadekán-1-ol',
  'hexadekanal',
  'Hexazion',
  'Hexitiazox',
  'hidrogénezett ásványolaj párlat',
  'hidrogénezett, etoxilált zsírsav-amin',
  'Hidrolizált fehérjék',
  'himexazol',
  'Hydrotaea aenescens',
  'Hypoaspis aculeifer',
  'Hypoaspis miles',
  'ichtiol',
  'illatanyag',
  'illóolajok',
  'Imazalil',
  'Imazamox',
  'Imazaquin',
  'Imidakloprid',
  'Indolil-vajsav',
  'Indoxakarb',
  'Ioxinil',
  'Ipkonazol',
  'Iprodion',
  'Iprovalikarb',
  'Izofetamid',
  'Izopirazam',
  'izoprén sztirén kopolimer',
  'izopropil-alkohol',
  'Izoproturon',
  'izoxaben',
  'izoxadifen-etil',
  'Izoxaflutol',
  'jodoszulfuron',
  'Kalcium-foszfid',
  'Kalcium-karbid',
  'kálcium-karbonát',
  'káliszappan',
  'kálium foszfonát',
  'kálium-aminopiralid',
  'Kálium-hidrogénkarbonát',
  'kálium-hipoklorit',
  'kálium-karbonát',
  'kálium-metabiszulfit',
  'kálium-nitrát',
  'kálium-oleát',
  'kálium-olivát',
  'Kaptán',
  'Karbamid',
  'Karbendazim',
  'karboxilát sztirol 1,3 butadién',
  'karboxi-metil-celullóz',
  'karboximetil-keményítő',
  'karboxin',
  'Karfentrazon-etil',
  'Kasugamicin',
  'Kén',
  'kletodim',
  'Klomazon',
  'Klopiralid',
  'Kloquintocet-mexil',
  'klórantraniliprol',
  'klórfacinon',
  'Kloridazon',
  'Klórmekvát',
  'klórpikrin',
  'Klórpirifosz',
  'Klórpirifosz-metil',
  'Klórprofám',
  'Klórszulfuron',
  'Klórtalonil',
  'Klórtoluron',
  'Klotianidin',
  'kolofónium (fenyőgyanta)',
  'Kovaföld',
  'kovaföld (szilikagél, diatomaföld)',
  'Krezoxim-metil',
  'kukurbitacin',
  'Kvarchomok',
  'Lambda-cihalotrin',
  'latex',
  'len olaj',
  'Lenacil',
  'Leptomastix dactylopii',
  'levendula olaj',
  'Linuron',
  'Lufeuron',
  'Macrocheles robustulus',
  'Macrolophus caliginosus',
  'Macrolophus pygmaeus',
  'Magnézium foszfid',
  'magnézium-foszfonát',
  'magnézium-szilikát hidrát',
  'magvas gomborka olaj',
  'maleinsav-hidrazid',
  'Maltodextrin',
  'Mandestrobin',
  'mandipropamid',
  'mandula olaj',
  'Mankoceb',
  'Marhafaggyú',
  'MCPA',
  'MCPB',
  'Mefenpir-dietil',
  'Mefentriflukonazol',
  'Mekoprop-P',
  'Mepikvát',
  'meptildinokap',
  'mészkén (kalcium-poliszulfid)',
  'metaflumizon',
  'Metalaxil',
  'Metalaxil-M',
  'metaldehid',
  'metám (ammónium)',
  'metám (nátrium)',
  'Metamitron',
  'Metazaklór',
  'metilált növényi olaj',
  'metilezett repceolaj',
  'metil-merkaptán',
  'metiloleát',
  'metilpalmitát',
  'Metiokarb',
  'Metiram',
  'metkamifen',
  'Metkonazol',
  'Metobromuron',
  'metomil',
  'Metoxifenozid',
  'Metrafenon',
  'Metribuzin',
  'metszulfuron-metil',
  'Mezoszulfuron',
  'Mezotrion',
  'Mica-ásvány',
  'miklobutanil',
  'milbemektin',
  'Mild Pepino Mosaic Virus isolate VC 1',
  'Monokálium-foszfát',
  'morfolin',
  'murgantiol',
  'Muscidifurax raptorellus',
  'napraforgóolaj',
  'napropamid',
  'Narancsolaj',
  'Nasonia vitripennis',
  'Nátrium-5-nitro-guajakolát',
  'nátrium-dioktil-szulfoszukcinát',
  'Nátrium-hexametafoszfát',
  'Nátrium-karboximetil-cellulóz',
  'Nátrium-lauril-szulfát',
  'Nátrium-o-nitrofenolát',
  'Nátrium-p-nitrofenolát',
  'Neoseiulus californicus',
  'Neoseiulus cucumeris',
  'Nesidiocoris tenuis',
  'n-fenil-ftálaminsav',
  'Nikoszulfuron',
  'Novaluron',
  'növényi kivonat',
  'növényi olaj',
  'növényi olajok metil észtere',
  'Növényi olajok/repceolaj',
  'Növényolaj',
  'n-vajsav',
  'NX 795 (texanol)',
  'Orius laevigatus',
  'Oxamil',
  'Oxatiapiprolin',
  'oxifluorfen',
  'Paecilomyces fumosoroseus strain Fe9901',
  'paklobutrazol',
  'paraffin viasz',
  'paraffinolaj',
  'Paraffinolajok / (CAS 64742-46-7)',
  'Paraffinolajok / (CAS 72623-86-0)',
  'Paraffinolajok / (CAS 8042-47-5)',
  'Paraffinolajok / (CAS 97862-82-3)',
  'Pelargonsav',
  'pencikuron',
  'Pendimetalin',
  'Penkonazol',
  'Penoxszulam',
  'pentiopirád',
  'Pepino mosaic virus strain CH2 isolate 1906',
  'perlit',
  'peru balzsam',
  'petoxamid',
  'Pharmarhabditis californica',
  'Phasmarhabditis hermaphrodita',
  'Phthorimaea operculella granulovirus (PhopGV)',
  'Phytoseiulus macropilis',
  'Phytoseiulus persimilis',
  'Pigment',
  'Pikloram',
  'Pikolinafen',
  'Pikoxistrobin',
  'Pimetrozin',
  'pinoxaden',
  'piperonil butoxid',
  'Piraflufen-etil',
  'Piraklostrobin',
  'Piretrinek',
  'piridaben',
  'piridalil',
  'Piridát',
  'Pirimetanil',
  'Pirimifosz-metil',
  'Pirimikarb',
  'piriofenon',
  'Piriproxifen',
  'piroxszulám',
  'poletiloxilát',
  'poli (dimetilxiloszán) polimer',
  'poliakrilamid',
  'Polialkilénoxiddal módosított heptametil-trisziloxán',
  'poliarilfenil-éter-foszfát amin-só',
  'polibutilén',
  'polidimetilsziloxán vizes emulziója',
  'Poliéter',
  'poliéterrel módosított trisziloxán',
  'Polietilén',
  'Polietilén glikol allil metil éter',
  'Polietilén-glikol monoallil-éter',
  'Poliizobutilén',
  'Poliklór-réz-ftalocianin',
  'poli-N-butil-akrilátsav vizes emulziója',
  'polipropilén-glicol',
  'poliszorbát',
  'Polivinil-pirrolidon',
  'Praon volucre',
  'Prohexadion',
  'prokloráz',
  'prokloráz rézklorid komplex',
  'Propakizafop',
  'Propamokarb',
  'propargit',
  'Propikonazol',
  'propilén-glikol',
  'Propineb',
  'Propizamid',
  'propizoklór',
  'propoxikarbazon',
  'Proquinazid',
  'proszulfokarb',
  'Proszulfuron',
  'Protiokonazol',
  'Pythium oligandrum',
  'quinmerak',
  'Quinoklamin',
  'Quinoxifen',
  'Quizalofop-P-etil',
  'quizalofop-P-tefuril',
  'ragasztóanyag',
  'répa kivonat',
  'Réz-hidroxid',
  'Réz-oxid',
  'rézoxikinolát',
  'Réz-oxiklorid',
  'Réz-szulfát',
  'rézszappan',
  'ricinusolaj',
  'Rimszulfuron',
  'S-abszcizinsav',
  'silvacol T',
  'Sitobion avenae',
  'S-metolaklór',
  'Spinetoram',
  'Spinozad',
  'Spirodiklofen',
  'spiromezifen',
  'spirotetramat',
  'Spiroxamin',
  'Steinernema carpocapsae',
  'Steinernema feltiae (EN05)',
  'Stratiolaelaps scimitus',
  'Streptomyces K61 (korábban S. griseoviridis)',
  'Sunsperse Red 112',
  'szabad és kombinált zsírsavak és foszforsav kev.',
  'szárított és fermentált dohánylevél törmelék',
  'szedaxán',
  'szilikon olaj',
  'szimetikon',
  'Szintofen',
  'szója lecitin',
  'szorbitán-laurát',
  'sztirol-akrilát kopolimer',
  'sztirol-butilakrilát kopolimer',
  'Szulfoszulfuron',
  'Szulfoxaflór',
  'Szulkotrion',
  'talkum',
  'tau-fluvalinát',
  'tebufenozid',
  'Tebufenpirad',
  'Tebukonazol',
  'Teflubenzuron',
  'teflutrin',
  'tejsav',
  'Tembotrion',
  'terbutilazin',
  'terpineol',
  'tetradekán-1-ol',
  'Tetrakonazol',
  'Tiabendazol',
  'Tiakloprid',
  'Tiametoxam',
  'tienkarbazon',
  'tienkarbazon-metil',
  'Tifenszulfuron-metil',
  'timol',
  'Tiofanát-metil',
  'Tiram (TMTD)',
  'Titán-dioxid',
  'Transeius montdorensis',
  'Triadimenol',
  'Triaszulfuron',
  'tribenuron',
  'Trichoderma asperellum (korábban T. harzianum)',
  'Trichoderma asperellum (strain T34)',
  'Trichoderma atroviride strain SC1',
  'Trichoderma harzianum Rifai',
  'Trichogramma achea',
  'Trichogramma brassicae',
  'Trichogramma evanescens',
  'Trichogramma pintoi',
  'Trifloxistrobin',
  'Triflumuron',
  'Trifluszulfuron',
  'Triklopir',
  'triklopir-butotil',
  'Trinexapak',
  'Trissolcus basalis',
  'trisziloxán',
  'Tritikonazol',
  'triton x-45',
  'Tritoszulfuron',
  'troklosen-Na',
  'Typhlodromus pyri',
  'Valifenal',
  'vas(III)-oxid (hematit)',
  'vas-ammónium-citrát',
  'Vas-foszfát',
  'Vas-pirofoszfát',
  'Vas-szulfát - Vas(II)-szulfát heptahidrát',
  'vazelinolaj',
  'vermikulit',
  'viasz',
  'vidrafű kivonat',
  'virágpoloskák',
  'vörös acsalapu kivonat',
  'xantángumi',
  'Zéta-cipermetrin',
  'Ziram',
  'Zoxamid',
  'zsíralkohol-alkoxilát',
  'zsírsavak metil észtere',
  'zsírsavak, növényi olajok metil észtere',
  'zsírsavak,C16-C18 telítetlen zsírsav,metil-észter',
  'zsírsav-észterek',
  'Zsírsav-etil-észter',
  'zsurlókivonat'
];

export const ActiveIngredientsSelect: React.FC<ActiveIngredientsSelectProps> = ({
  selectedIngredients,
  onChange
}) => {
  const [isOpen, setIsOpen] = useState(false);
  const [searchQuery, setSearchQuery] = useState('');
  const availableIngredients = React.useMemo(() => {
    return Array.from(new Set([...PREDEFINED_INGREDIENTS, ...selectedIngredients]));
  }, [selectedIngredients]);
  
  const containerRef = useRef<HTMLDivElement>(null);

  // Handle outside click to close dropdown
  useEffect(() => {
    const handleOutsideClick = (event: MouseEvent) => {
      if (containerRef.current && !containerRef.current.contains(event.target as Node)) {
        setIsOpen(false);
      }
    };
    document.addEventListener('mousedown', handleOutsideClick);
    return () => document.removeEventListener('mousedown', handleOutsideClick);
  }, []);

  const handleToggle = (ingredient: string) => {
    if (selectedIngredients.includes(ingredient)) {
      onChange(selectedIngredients.filter(item => item !== ingredient));
    } else {
      onChange([...selectedIngredients, ingredient]);
    }
  };

  const handleAddCustom = () => {
    const trimmed = searchQuery.trim();
    if (trimmed && !availableIngredients.some(item => item.toLowerCase() === trimmed.toLowerCase())) {
      onChange([...selectedIngredients, trimmed]);
      setSearchQuery('');
    }
  };

  const filtered = availableIngredients.filter(ingredient =>
    ingredient.toLowerCase().includes(searchQuery.toLowerCase())
  );

  const exactMatchExists = availableIngredients.some(
    ingredient => ingredient.toLowerCase() === searchQuery.trim().toLowerCase()
  );

  return (
    <div className="active-ingredients-container" ref={containerRef} style={{ position: 'relative', width: '100%' }}>
      {/* Selected tags row */}
      {selectedIngredients.length > 0 && (
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '6px', marginBottom: '8px' }}>
          {selectedIngredients.map(ingredient => (
            <span
              key={ingredient}
              style={{
                display: 'flex',
                alignItems: 'center',
                gap: '4px',
                padding: '4px 8px',
                borderRadius: '6px',
                fontSize: '11px',
                fontWeight: 600,
                backgroundColor: 'var(--primary-light)',
                color: 'var(--primary)',
                border: '1px solid rgba(0, 104, 55, 0.15)'
              }}
            >
              <span>{ingredient}</span>
              <button
                type="button"
                onClick={() => handleToggle(ingredient)}
                style={{
                  border: 'none',
                  background: 'none',
                  padding: 0,
                  color: 'var(--primary)',
                  cursor: 'pointer',
                  display: 'flex',
                  alignItems: 'center'
                }}
              >
                <X size={12} />
              </button>
            </span>
          ))}
        </div>
      )}

      {/* Main trigger button */}
      <button
        type="button"
        className="form-select"
        style={{
          display: 'flex',
          justifyContent: 'space-between',
          alignItems: 'center',
          textAlign: 'left',
          width: '100%',
          minHeight: '38px',
          height: 'auto',
          paddingRight: '12px',
          boxSizing: 'border-box'
        }}
        onClick={() => setIsOpen(!isOpen)}
      >
        <span style={{ color: selectedIngredients.length > 0 ? 'var(--text-primary)' : 'var(--text-light)', fontSize: '13px' }}>
          {selectedIngredients.length > 0
            ? `${selectedIngredients.length} hatóanyag kiválasztva`
            : 'Válassz hatóanyagokat...'}
        </span>
        <ChevronDown size={16} style={{ color: 'var(--text-secondary)' }} />
      </button>

      {/* Dropdown list */}
      {isOpen && (
        <div
          style={{
            position: 'absolute',
            top: '100%',
            left: 0,
            width: '100%',
            backgroundColor: 'var(--bg-card)',
            border: '1px solid var(--border)',
            borderRadius: '8px',
            boxShadow: '0 8px 16px rgba(0,0,0,0.1)',
            zIndex: 100,
            marginTop: '4px',
            maxHeight: '260px',
            display: 'flex',
            flexDirection: 'column',
            overflow: 'hidden'
          }}
        >
          {/* Search bar */}
          <div style={{ display: 'flex', alignItems: 'center', padding: '8px', borderBottom: '1px solid var(--border)', gap: '6px' }}>
            <Search size={14} style={{ color: 'var(--text-secondary)', marginLeft: '4px' }} />
            <input
              type="text"
              placeholder="Keresés..."
              value={searchQuery}
              onChange={(e) => setSearchQuery(e.target.value)}
              style={{
                border: 'none',
                outline: 'none',
                fontSize: '12px',
                width: '100%',
                backgroundColor: 'transparent',
                color: 'var(--text-primary)'
              }}
            />
          </div>

          {/* List items */}
          <div style={{ overflowY: 'auto', flex: 1, padding: '4px' }}>
            {filtered.map(ingredient => {
              const isChecked = selectedIngredients.includes(ingredient);
              return (
                <div
                  key={ingredient}
                  onClick={() => handleToggle(ingredient)}
                  style={{
                    display: 'flex',
                    alignItems: 'center',
                    justifyContent: 'space-between',
                    padding: '8px 12px',
                    borderRadius: '6px',
                    cursor: 'pointer',
                    fontSize: '13px',
                    backgroundColor: isChecked ? 'var(--bg-app)' : 'transparent',
                    color: isChecked ? 'var(--primary)' : 'var(--text-primary)',
                    transition: 'background-color 0.1s'
                  }}
                >
                  <span>{ingredient}</span>
                  {isChecked && <Check size={14} style={{ color: 'var(--primary)' }} />}
                </div>
              );
            })}

            {/* Custom add item */}
            {searchQuery.trim() !== '' && !exactMatchExists && (
              <button
                type="button"
                onClick={handleAddCustom}
                style={{
                  display: 'flex',
                  alignItems: 'center',
                  gap: '6px',
                  width: '100%',
                  padding: '8px 12px',
                  border: 'none',
                  background: 'none',
                  color: 'var(--primary)',
                  fontSize: '12px',
                  fontWeight: 600,
                  cursor: 'pointer',
                  textAlign: 'left',
                  borderTop: '1px dashed var(--border)'
                }}
              >
                <Plus size={14} />
                <span>Hozzáadás hatóanyagként: "{searchQuery.trim()}"</span>
              </button>
            )}

            {filtered.length === 0 && searchQuery.trim() === '' && (
              <div style={{ padding: '16px', textAlign: 'center', fontSize: '12px', color: 'var(--text-secondary)' }}>
                Nincs elérhető hatóanyag.
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
